clc
clear
close all

root=fileparts(mfilename('fullpath'));
addpath(root,fullfile(root,'data','cec2017'))
cd(fullfile(root,'data','cec2017'))

functionIDs=[1 3 9 12 22];
repeatIDs=21:23;
D=30;
population=50;
maxEvaluations=60000;
seedBase=20271004;
lb=-100*ones(1,D);
ub=100*ones(1,D);
workerCount=4;
batchSize=4;

variants={ ...
    struct('Name','V1-A-TracingOnly','SearchCore','base','EliteGuidance',false,'TracingAcceptance',true), ...
    struct('Name','V1-B-EliteOnly','SearchCore','elite','EliteGuidance',true,'TracingAcceptance',false)};

stamp=char(datetime('now','Format','yyyyMMdd_HHmmss'));
resultDir=fullfile(root,'results','cec',['cec2017_v1_mechanism_lowfe_' stamp]);
mkdir(resultDir);

jobs=struct('FunctionID',{},'Run',{},'Variant',{},'SearchCore',{}, ...
    'EliteGuidance',{},'TracingAcceptance',{},'InitSeed',{}, ...
    'SearchSeed',{},'InitialPopulation',{});
count=0;
for functionID=functionIDs
    for repeat=repeatIDs
        initSeed=seedBase+repeat;
        rng(initSeed,'twister')
        initialPopulation=lb+rand(population,D).*(ub-lb);
        for v=1:numel(variants)
            count=count+1;
            spec=variants{v};
            jobs(count)=struct('FunctionID',functionID,'Run',repeat, ...
                'Variant',spec.Name,'SearchCore',spec.SearchCore, ...
                'EliteGuidance',spec.EliteGuidance, ...
                'TracingAcceptance',spec.TracingAcceptance, ...
                'InitSeed',initSeed,'SearchSeed',initSeed+100000, ...
                'InitialPopulation',initialPopulation);
        end
    end
end

pool=gcp('nocreate');
if isempty(pool)
    parpool('local',workerCount);
elseif pool.NumWorkers~=workerCount
    delete(pool);
    parpool('local',workerCount);
end

records=cell(numel(jobs),1);
curves=cell(numel(jobs),1);
for first=1:batchSize:numel(jobs)
    last=min(first+batchSize-1,numel(jobs));
    batch=jobs(first:last);
    batchResults=cell(numel(batch),1);
    parfor j=1:numel(batch)
        job=batch(j);
        f=@(x)CEC2017Function(x,job.FunctionID);
        state=struct('lowerBound',lb,'upperBound',ub, ...
            'maxEvaluations',maxEvaluations,'initialPopulation',job.InitialPopulation, ...
            'actionMode','fixed2','rlMode','modeAwareV41','seekingMode','range', ...
            'seekSelection','globalCap2','searchCore',job.SearchCore, ...
            'eliteGuidance',job.EliteGuidance, ...
            'tracingElitistAcceptance',job.TracingAcceptance, ...
            'SMP',5,'recoveryEnabled',false,'useModePreserving',true, ...
            'ablation',struct('useCatScreen',true,'useCandidateScreen',true, ...
                'useRL',false));
        [Best,T,info]=DSS_RLCSO(f,state,ceil(maxEvaluations/population), ...
            population,job.SearchSeed);
        assert(info.Evaluations==maxEvaluations && numel(T)==maxEvaluations)
        assert(all(isfinite(T)) && all(info.EvaluationsPerRound==5))
        assert(all(info.ActualTracingEvaluations==2))
        assert(all(info.ActualSeekingEvaluations==3))
        assert(max(abs(info.ModeAllocationError),[],'all')==0)
        record=struct('Function',sprintf('F%02d',job.FunctionID), ...
            'FunctionID',job.FunctionID,'Algorithm',job.Variant,'Run',job.Run, ...
            'SearchCore',job.SearchCore,'EliteGuidance',job.EliteGuidance, ...
            'TracingAcceptance',job.TracingAcceptance,'SMP',5, ...
            'InitSeed',job.InitSeed,'SearchSeed',job.SearchSeed, ...
            'Evaluations',info.Evaluations,'BestCost',Best.Cost, ...
            'BestError',max(0,Best.Cost-100*job.FunctionID), ...
            'Seconds',info.Seconds, ...
            'Error30FE',max(0,T(round(0.3*maxEvaluations))-100*job.FunctionID), ...
            'Error60FE',max(0,T(round(0.6*maxEvaluations))-100*job.FunctionID), ...
            'Error80FE',max(0,T(round(0.8*maxEvaluations))-100*job.FunctionID));
        nodes=(3000:3000:maxEvaluations)';
        curve=table(repmat(job.FunctionID,numel(nodes),1), ...
            repmat({job.Variant},numel(nodes),1),repmat(job.Run,numel(nodes),1), ...
            nodes,max(0,T(nodes)-100*job.FunctionID), ...
            'VariableNames',{'FunctionID','Algorithm','Run','FE','BestError'});
        batchResults{j}=struct('record',record,'curve',curve);
    end
    for j=1:numel(batch)
        records{first+j-1}=batchResults{j}.record;
        curves{first+j-1}=batchResults{j}.curve;
    end
    writetable(struct2table([records{1:last}]), ...
        fullfile(resultDir,'raw_runs_checkpoint.csv'));
    writetable(vertcat(curves{1:last}), ...
        fullfile(resultDir,'convergence_checkpoint.csv'));
    fprintf('Completed %d/%d runs with %d workers\n',last,numel(jobs),workerCount);
end

rawRuns=struct2table([records{:}]);
writetable(rawRuns,fullfile(resultDir,'raw_runs.csv'));
writetable(vertcat(curves{:}),fullfile(resultDir,'convergence.csv'));

summaryRecords=cell(numel(functionIDs)*numel(variants),1);
k=0;
for functionID=functionIDs
    for v=1:numel(variants)
        rows=rawRuns(rawRuns.FunctionID==functionID & ...
            strcmp(rawRuns.Algorithm,variants{v}.Name),:);
        k=k+1;
        summaryRecords{k}=struct('Function',sprintf('F%02d',functionID), ...
            'FunctionID',functionID,'Algorithm',variants{v}.Name,'Runs',height(rows), ...
            'MeanError',mean(rows.BestError),'StdError',std(rows.BestError), ...
            'MedianError',median(rows.BestError),'MinError',min(rows.BestError), ...
            'MeanSeconds',mean(rows.Seconds),'MeanError30FE',mean(rows.Error30FE), ...
            'MeanError60FE',mean(rows.Error60FE),'MeanError80FE',mean(rows.Error80FE));
    end
end
writetable(struct2table([summaryRecords{:}]),fullfile(resultDir,'summary.csv'));

readme={ ...
    '# V1 mechanism ablation at 60k FE', ...
    '', ...
    'This experiment separates the two changes included in V1-Elite:', ...
    '', ...
    '- V1-A-TracingOnly: original gbest-based search, with Tracing accepting only an improvement over the parent.', ...
    '- V1-B-EliteOnly: historical-elite guidance, with the original unconditional Tracing acceptance.', ...
    '- The complete V1-Elite reference is retained in `cec2017_search_core_20261009_091923`.', ...
    '', ...
    'All runs use D=30, population=50, 60,000 FE, Range Seeking, Global-Cap2, MR=0.4, SMP=5, no Recovery, and paired seeds 21:23 on F1, F3, F9, F12 and F22.', ...
    '', ...
    'The script checks exact FE accounting and the 2 Tracing + 3 Seeking allocation for every run.', ...
    ''};
fid=fopen(fullfile(resultDir,'README.md'),'w');
fprintf(fid,'%s\n',readme{:});
fclose(fid);

delete(gcp('nocreate'))
fprintf('Saved mechanism ablation to %s\n',resultDir);

function value=CEC2017Function(x,functionID)
    value=cec17_func(x',functionID);
    value=value(1);
end

