clc
clear
close all

root=fileparts(mfilename('fullpath'));
addpath(root,fullfile(root,'data','cec2017'))
cd(fullfile(root,'data','cec2017'))

functionIDs=[4 5 7 8 11 13 14 16 17 18 20 21 23 24 25 27 28 29 30];
repeatIDs=31:33;
D=30;
population=50;
maxEvaluations=60000;
seedBase=20271004;
lb=-100*ones(1,D);
ub=100*ones(1,D);
workerCount=4;
batchSize=4;

variants={ ...
    struct('Name','V1-Reference','TracingDecay',false,'VirtualTracing',false), ...
    struct('Name','D1-TracingDecay','TracingDecay',true,'VirtualTracing',false), ...
    struct('Name','D3-Both','TracingDecay',true,'VirtualTracing',true), ...
    struct('Name','CLPSO','TracingDecay',false,'VirtualTracing',false)};

stamp=char(datetime('now','Format','yyyyMMdd_HHmmss'));
resultDir=fullfile(root,'results','cec',['cec2017_d3_extension_' stamp]);
mkdir(resultDir);

jobs=struct('FunctionID',{},'Run',{},'Variant',{},'TracingDecay',{}, ...
    'VirtualTracing',{},'InitSeed',{},'SearchSeed',{},'InitialPopulation',{});
count=0;
for functionID=functionIDs
    for repeat=repeatIDs
        initSeed=seedBase+repeat;
        rng(initSeed,'twister')
        initialPopulation=lb+rand(population,D).*(ub-lb);
        for v=1:numel(variants)
            count=count+1;
            spec=variants{v};
            jobs(count)=struct('FunctionID',functionID,'Run',repeat, ...
                'Variant',spec.Name,'TracingDecay',spec.TracingDecay, ...
                'VirtualTracing',spec.VirtualTracing,'InitSeed',initSeed, ...
                'SearchSeed',initSeed+100000, ...
                'InitialPopulation',initialPopulation);
        end
    end
end

pool=gcp('nocreate');
if isempty(pool)
    parpool('local',workerCount);
elseif pool.NumWorkers~=workerCount
    delete(pool);
    parpool('local',workerCount);
end

records=cell(numel(jobs),1);
curves=cell(numel(jobs),1);
for first=1:batchSize:numel(jobs)
    last=min(first+batchSize-1,numel(jobs));
    batch=jobs(first:last);
    batchResults=cell(numel(batch),1);
    parfor j=1:numel(batch)
        job=batch(j);
        f=@(x)CEC2017Function(x,job.FunctionID);
        if strcmp(job.Variant,'CLPSO')
            state=struct('lowerBound',lb,'upperBound',ub, ...
                'maxEvaluations',maxEvaluations,'initialPopulation',job.InitialPopulation);
            [Best,T,info]=CLPSO_CEC(f,state,ceil(maxEvaluations/population), ...
                population,job.SearchSeed);
        else
            state=struct('lowerBound',lb,'upperBound',ub, ...
                'maxEvaluations',maxEvaluations,'initialPopulation',job.InitialPopulation, ...
                'actionMode','fixed2','rlMode','modeAwareV41','seekingMode','range', ...
                'seekSelection','globalCap2','searchCore','elite','eliteGuidance',true, ...
                'tracingElitistAcceptance',true,'tracingDecay',job.TracingDecay, ...
                'virtualTracing',job.VirtualTracing,'SMP',5, ...
                'recoveryEnabled',false,'useModePreserving',true, ...
                'ablation',struct('useCatScreen',true,'useCandidateScreen',true, ...
                    'useRL',false));
            [Best,T,info]=DSS_RLCSO(f,state,ceil(maxEvaluations/population), ...
                population,job.SearchSeed);
            assert(info.Evaluations==maxEvaluations && numel(T)==maxEvaluations)
            assert(all(isfinite(T)) && all(info.EvaluationsPerRound==5))
            assert(all(info.ActualTracingEvaluations==2))
            assert(all(info.ActualSeekingEvaluations==3))
            assert(all(info.BudgetFillRate==1))
            assert(max(abs(info.ModeAllocationError),[],'all')==0)
            assert(max(info.SeekingMaxParentEvaluations)<=2)
        end
        assert(info.Evaluations==maxEvaluations && numel(T)==maxEvaluations)
        assert(all(isfinite(T)))
        functionValue=100*job.FunctionID;
        record=struct('Function',sprintf('F%02d',job.FunctionID), ...
            'FunctionID',job.FunctionID,'Algorithm',job.Variant,'Run',job.Run, ...
            'TracingDecay',job.TracingDecay,'VirtualTracing',job.VirtualTracing, ...
            'InitSeed',job.InitSeed,'SearchSeed',job.SearchSeed, ...
            'Evaluations',info.Evaluations,'BestCost',Best.Cost, ...
            'BestError',max(0,Best.Cost-functionValue),'Seconds',info.Seconds, ...
            'Error30FE',max(0,T(round(0.3*maxEvaluations))-functionValue), ...
            'Error60FE',max(0,T(round(0.6*maxEvaluations))-functionValue), ...
            'Error80FE',max(0,T(round(0.8*maxEvaluations))-functionValue));
        nodes=(3000:3000:maxEvaluations)';
        curve=table(repmat(job.FunctionID,numel(nodes),1), ...
            repmat({job.Variant},numel(nodes),1),repmat(job.Run,numel(nodes),1), ...
            nodes,max(0,T(nodes)-functionValue), ...
            'VariableNames',{'FunctionID','Algorithm','Run','FE','BestError'});
        batchResults{j}=struct('record',record,'curve',curve);
    end
    for j=1:numel(batch)
        records{first+j-1}=batchResults{j}.record;
        curves{first+j-1}=batchResults{j}.curve;
    end
    writetable(struct2table([records{1:last}]), ...
        fullfile(resultDir,'raw_runs_checkpoint.csv'));
    writetable(vertcat(curves{1:last}), ...
        fullfile(resultDir,'convergence_checkpoint.csv'));
    fprintf('Completed %d/%d runs with %d workers\n',last,numel(jobs),workerCount);
end

rawRuns=struct2table([records{:}]);
writetable(rawRuns,fullfile(resultDir,'raw_runs.csv'));
writetable(vertcat(curves{:}),fullfile(resultDir,'convergence.csv'));

summaryRecords=cell(numel(functionIDs)*numel(variants),1);
k=0;
for functionID=functionIDs
    for v=1:numel(variants)
        rows=rawRuns(rawRuns.FunctionID==functionID & ...
            strcmp(rawRuns.Algorithm,variants{v}.Name),:);
        if isempty(rows)
            continue
        end
        k=k+1;
        summaryRecords{k}=struct('Function',sprintf('F%02d',functionID), ...
            'FunctionID',functionID,'Algorithm',variants{v}.Name,'Runs',height(rows), ...
            'MeanError',mean(rows.BestError),'StdError',std(rows.BestError), ...
            'MedianError',median(rows.BestError),'MinError',min(rows.BestError), ...
            'MeanSeconds',mean(rows.Seconds),'MeanError30FE',mean(rows.Error30FE), ...
            'MeanError60FE',mean(rows.Error60FE),'MeanError80FE',mean(rows.Error80FE));
    end
end
writetable(struct2table([summaryRecords{1:k}]),fullfile(resultDir,'summary.csv'));

readme={ ...
    '# D3 extension validation at 60k FE', ...
    '', ...
    '- Functions: F4, F5, F7, F8, F11, F13, F14, F16, F17, F18, F20, F21, F23, F24, F25, F27, F28, F29 and F30.', ...
    '- Dimension: D=30; population: 50; budget: 60,000 FE.', ...
    '- Repeats: 31:33 with paired initial populations for all four algorithms.', ...
    '- V1-Reference: tracing decay off and virtual tracing off.', ...
    '- D1-TracingDecay: tracing inertia decreases from 0.9 to 0.4.', ...
    '- D3-Both: D1 plus virtual tracing with real-position rollback after rejected evaluations.', ...
    '- CLPSO is the external same-budget reference.', ...
    '- All DSS variants use Range Seeking, Global-Cap2, MR=0.4, SMP=5, no Recovery and no RL.', ...
    '- The script checks exact FE accounting and the 2 Tracing + 3 Seeking allocation.', ...
    ''};
fid=fopen(fullfile(resultDir,'README.md'),'w');
fprintf(fid,'%s\n',readme{:});
fclose(fid);

delete(gcp('nocreate'))
fprintf('Saved D3 extension validation to %s\n',resultDir);

function value=CEC2017Function(x,functionID)
    value=cec17_func(x',functionID);
    value=value(1);
end
